### PR TITLE
exclude invalid versions from existing tags

### PR DESCRIPTION
**Pull request by minrk**
semver.parse returns null for invalid versions, and null.prerelease is undefined

filter existing tags to only valid versions before parsing

Otherwise, the existence of *any* tags which are not valid semvers, prevents the calculation of existing tags

### CODE REVIEW

**Comment by consideRatio** [comment]
Hmmmmm, the JS source needs to be compiled etc. You can do `npm run all` and I think it does so.

There is a workflow to automate updating this repo when the source code changes etc, but I don't think its triggering for some reason.

**Review by consideRatio — APPROVED** [review]
The src/ changes looks good to me, now we just need the dist/ changes.

**Comment by minrk** [comment]
dist regenerated

**Comment by manics** [comment]
> There is a workflow to automate updating this repo's PRs when the source code changes etc, but I don't think its triggering for some reason.

It only runs on the submitter's branch as it needs permission to push back to the branch ... which requires ... `GITHUB_TOKEN` 😀. Probably actions aren't enabled on the fork https://github.com/minrk/action-major-minor-tag-calculator/actions

**Pull request merged**
