### PR TITLE
use loose semver parsing to accept more prerelease formats

### PR DESCRIPTION
**Pull request by minrk**
accepts standards like 1.2.3b4 as seen in Python, etc.

seems like the shortest path to https://github.com/jupyterhub/jupyterhub/issues/3612

### CODE REVIEW

**Comment by consideRatio** [comment]
Can you add a test case to the existing tests, verifying that 2.0.0b1 should return `["2.0.0b1"]` rather than for example `["2", "2.0", "2.0.0", "2.0.0b1"]` ?

Nice find with the `loose` parameter! This looks great to me if it works as intended!

**Comment by consideRatio** [comment]
For reference, this is where I read about `loose`: https://github.com/npm/node-semver#functions

**Comment by consideRatio** [comment]
:heart: @manics having written tests

**Comment by manics** [comment]
I agree a test would be good. Should be easy to add, just copy and paste one of the existing cases e.g.
https://github.com/jupyterhub/action-major-minor-tag-calculator/blob/0cfbca09dd69e06a7141309336ac11a9b7c79aa7/__tests__/main.test.js#L207-L215
or
https://github.com/jupyterhub/action-major-minor-tag-calculator/blob/0cfbca09dd69e06a7141309336ac11a9b7c79aa7/__tests__/main.test.js#L183-L205

Assuming it all works, shall we release as `2.0.0` since this is a change in behaviour? Does anyone have any other issues or annoyances involving a breaking change that they want to get into `2.0.0`?

**Comment by minrk** [comment]
I only saw 'test.js', I missed `__tests__`. Test added (and it works now, thanks to the test!)

**Comment by consideRatio** [comment]
LGTM! Thanks @minrk!

**Pull request merged**
