### PR TITLE
Add suffix input and support empty strings in prefix/suffix

### PR DESCRIPTION
**Pull request by consideRatio**
Adds a `suffix` input and supports specifying an empty string element in a list of prefixes/suffixes via either `prefix` or `suffix` input by specifying `""` instead.

Having `suffix` next to `prefix` is probably generally useful, but I have a use case for jupyterhub/jupyter-remote-desktop-proxy to publish the same image with the suffixes `""` and `"-tiger"` as planned via https://github.com/jupyterhub/jupyter-remote-desktop-proxy/issues/88.

This is an example of how I'd use it there:

```yaml
        # ...
        with:
          prefix: |
            quay.io/jupyterhub/jupyter-remote-desktop-proxy:
          suffix: |
            ""
            -tigervnc
          # ...
```

### CODE REVIEW

**Comment by consideRatio** [comment]
@manics sorry for pinging for review and pushing changes after, I won't touch this further now though.

**Comment by consideRatio** [comment]
> Have you thought about using `""` to mean the empty string?

Yes! I found an the issue is that we had a whitespace and/or comma deliminated list for prefix, so doing that would be weird there. I looked to use the same syntax for suffix/prefix, and to not make a breaking change. I also concluded that if i made use of new lines as separators for suffix, it would end up making users write hard-to-write-correctly and hard-to-understand yaml config.

**Comment by manics** [comment]
I meant (basically) `'""'` not just `""`. So
```yaml
          suffix: |
            ""
            -tigervnc
```
```yaml
          suffix: "", -tigervnc
```

**Comment by consideRatio** [comment]
Ah, okay - we can do that also! I'll update this PR to reflect that when i'm at a computer next time!

**Review by manics — COMMENTED** [review]
Code looks good!

The new parameter is missing from the README:
https://github.com/consideRatio/action-major-minor-tag-calculator/tree/pr/add-suffix-input?tab=readme-ov-file#optional-input-parameters

**Comment by consideRatio** [comment]
Thank you @manics, great catches!

**Comment by consideRatio** [comment]
Force pushed away repeated `auto-format and update dist stuff` commits.

**Review by manics — APPROVED** [review]

**Pull request merged**
