### PR TITLE
Stop bumping dev deps and group production PRs

### LINKED ISSUE #316: Is it possible to redefine package.json in a way to reduce dependacy bumps?
We have various dev-dependencies, I figure it makes sense to not manually have them bumped in the first place now that I think about it.

Another idea that I'm also interested in was if we can avoid bumping at all in situations like in #310, where a dev dependency was bumped:

```diff
-"nock": "^13.3.1",
+"nock": "^13.3.3",
```

### PR DESCRIPTION
**Pull request by consideRatio**
- Closes #316 by reducing the PR bump noise to at most one package.json bump PR a month, by no longer bumping dev dependencies, and grouping bumps of other dependencies.

Let's get this merged before November 1!

### CODE REVIEW

**Comment by manics** [comment]
Sounds like a good idea! Is there a reason we need to exclude dev dependencies- couldn't we just update everything in one go?

**Comment by consideRatio** [comment]
I see some value in separating prod from dev dependencies, but if we are to bump both - maybe I'd prefer one less PR by combing them.

My preferences ordered, but happy to go based on yours:
1. prod only bumped
2. prod and dev bumped
3. prod and dev bumped, grouped by prod and dev separetely, so two PRs are opened monthly for this

Do you prefer to go with option 2, bumping dev deps also in the same PR @manics?

**Comment by manics** [comment]
Yes, I was thinking of bumping prod+dev (and anything else!) in one PR. Unless there's a good reason not to bump dev dependencies?

**Comment by consideRatio** [comment]
> Unless there's a good reason not to bump dev dependencies?

Not really, but I figured there wasn't a strong case for bumping them either. With that I vaguely reasoned that we could opt to not be bothered doing it monthly to avoid clutter the PRs we are to review with non-important changes to review.

---

I pushed a commit that I think gets it done!

**Review by manics — APPROVED** [review]
Thanks!

**Comment by consideRatio** [comment]
Thank you @manics!!!

**Pull request merged**
